name: 🛠 Auto-update README

on:
  push:
    paths:
      - "**.py"
      - "**.ipynb"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Auto-update README folder structure
        run: |
          tree -I '.git|.github|venv|__pycache__' -L 2 -F > structure.txt
          echo '```' > tmp && cat structure.txt >> tmp && echo '```' >> tmp
          awk '/## Project Structure/{print; getline; while ($0 ~ /^`/) getline; system("cat tmp"); next}1' README.md > new_README.md
          mv new_README.md README.md

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "🔄 Auto-update folder structure in README" || echo "No changes to commit"
          git push
